name: assihnment_technolitocs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.4.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  image_picker:
  cached_network_image:
  flutter_svg: ^2.1.0
  flutter_riverpod:
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1
  webview_flutter: ^4.13.0
  dotted_border: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Movatif
      fonts:
        - asset: assets/fonts/Movatif-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
